# Generated by Django 5.2.11 on 2026-02-18 09:14

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('hero', 5), ('about', 8), ('services', 15), ('projects_showcase', 20), ('contact', 23), ('location', 26), ('richtext', 28), ('gallery', 31), ('cta', 34), ('testimonials', 40), ('spacer', 42)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'Læs mere', 'required': False}), 4: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('image', 2), ('button_text', 3), ('button_link', 4)]], {}), 6: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Venstre'), ('right', 'Højre')]}), 8: ('wagtail.blocks.StructBlock', [[('heading', 0), ('text', 6), ('image', 2), ('image_position', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'default': 'Vores ydelser', 'required': True}), 10: ('wagtail.blocks.CharBlock', (), {}), 11: ('wagtail.blocks.RichTextBlock', (), {}), 12: ('wagtail.blocks.CharBlock', (), {'help_text': 'Bootstrap Icon class, e.g. bi-hammer', 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('title', 10), ('description', 11), ('icon', 12)]], {}), 14: ('wagtail.blocks.ListBlock', (13,), {}), 15: ('wagtail.blocks.StructBlock', [[('heading', 9), ('services', 14)]], {}), 16: ('wagtail.blocks.CharBlock', (), {'default': 'Aktuelle projekter', 'required': True}), 17: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['projects.ProjectIndexPage'], 'required': False}), 18: ('wagtail.blocks.IntegerBlock', (), {'default': 3, 'max_value': 12, 'min_value': 1}), 19: ('wagtail.blocks.CharBlock', (), {'default': 'Alle projekter', 'required': False}), 20: ('wagtail.blocks.StructBlock', [[('heading', 16), ('projects_page', 17), ('count', 18), ('button_text', 19)]], {}), 21: ('wagtail.blocks.CharBlock', (), {'default': 'Kontakt os', 'required': True}), 22: ('wagtail.blocks.EmailBlock', (), {'required': False}), 23: ('wagtail.blocks.StructBlock', [[('heading', 21), ('text', 1), ('address', 1), ('phone', 1), ('email', 22)]], {}), 24: ('wagtail.blocks.CharBlock', (), {'default': 'Find os', 'required': True}), 25: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Google Maps embed HTML or similar', 'required': False}), 26: ('wagtail.blocks.StructBlock', [[('heading', 24), ('address', 0), ('map_embed', 25)]], {}), 27: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('white', 'Hvid'), ('light', 'Lys'), ('dark', 'Mørk')]}), 28: ('wagtail.blocks.StructBlock', [[('heading', 1), ('content', 11), ('background', 27)]], {}), 29: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 30: ('wagtail.blocks.ListBlock', (29,), {}), 31: ('wagtail.blocks.StructBlock', [[('heading', 1), ('images', 30)]], {}), 32: ('wagtail.blocks.URLBlock', (), {'help_text': 'External URL (bruges hvis ingen side er valgt)', 'required': False}), 33: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primær'), ('dark', 'Mørk'), ('light', 'Lys')]}), 34: ('wagtail.blocks.StructBlock', [[('heading', 0), ('text', 1), ('button_text', 0), ('button_link', 4), ('button_url', 32), ('background', 33)]], {}), 35: ('wagtail.blocks.CharBlock', (), {'default': 'Hvad vores kunder siger', 'required': False}), 36: ('wagtail.blocks.TextBlock', (), {}), 37: ('wagtail.blocks.CharBlock', (), {'help_text': "e.g. 'Privatkunde' or 'Virksomhed'", 'required': False}), 38: ('wagtail.blocks.StructBlock', [[('quote', 36), ('author', 10), ('role', 37)]], {}), 39: ('wagtail.blocks.ListBlock', (38,), {}), 40: ('wagtail.blocks.StructBlock', [[('heading', 35), ('testimonials', 39)]], {}), 41: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('small', 'Lille (2rem)'), ('medium', 'Medium (4rem)'), ('large', 'Stor (8rem)')]}), 42: ('wagtail.blocks.StructBlock', [[('height', 41)]], {})})),
            ],
            options={
                'verbose_name': 'Fleksibel side',
                'verbose_name_plural': 'Fleksible sider',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Snedkeri Meier', help_text='Virksomhedens navn (vises i navbar, footer og titel)', max_length=255)),
                ('tagline', models.CharField(default='Traditionelt håndværk med moderne teknik.', help_text='Sloganet der vises i footeren', max_length=500)),
                ('opening_hours', models.TextField(blank=True, default='Man - Fre: 7:00 - 17:00\nLør: 8:00 - 12:00\nSøn: Lukket', help_text='Åbningstider (ét linje per tidspunkt)')),
                ('footer_text', models.CharField(blank=True, default='', help_text='Valgfri copyright-tekst i footeren. Tom = autogenereret.', max_length=500)),
                ('address', models.CharField(blank=True, default='', help_text='Virksomhedens adresse (vises i footer)', max_length=255)),
                ('phone', models.CharField(blank=True, default='', help_text='Telefonnummer (vises i footer)', max_length=50)),
                ('email', models.EmailField(blank=True, default='', help_text='E-mail (vises i footer)', max_length=254)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Indstillinger',
            },
        ),
    ]
